version: 2.1

jobs:
  prepare:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Prepare Workspace
          command: echo "Preparing workspace..."

  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Set Terraform Credentials
          command: |
            mkdir -p ~/.terraform.d
            echo '{"credentials":{"app.terraform.io":{"token":"'$TF_API_TOKEN'"}}}' > ~/.terraform.d/credentials.tfrc.json
       


      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Set up AWS Credentials
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - run:    
          name: Terraform Plan
          command: terraform plan -out=tfplan_tgw
      - persist_to_workspace:
          root: .
          paths:
            - tfplan_tgw
   
  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Set up AWS Credentials
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - run:
          name: Terraform Apply
          command: terraform apply "/workspace/tfplan_tgw"           
            

  

workflows:
  version: 2
  deploy:
    jobs:
      - prepare
      - plan
      - approval:  # Add manual approval step
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - approval
