version: 2.1

jobs:
  prepare:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Prepare Workspace
          command: echo "Preparing workspace..."

  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Set Terraform Credentials
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> ~/.aws/credentials
            export TF_API_TOKEN=$TF_API_TOKEN 
      - run:
          name: Terraform Init
          command: terraform init

      - run:    
          name: Terraform Plan
          command: terraform plan -out=tfplan_tgw
      - persist_to_workspace:
          root: ~/
          paths:
            - .aws
            - tfplan_tgw
  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - attach_workspace:
          at: /workspace
      - run:
          name: Restore AWS and Terraform Credentials
          command: |
            cp -r /workspace/.aws ~/
            export TF_TOKEN=$TF_TOKEN
      - run:
          name: Terraform Apply
          command: terraform apply "/workspace/tfplan_tgw"      
            

  

workflows:
  version: 2
  deploy:
    jobs:
      - prepare
      - plan
      - approval:  # Add manual approval step
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - approval
