version: 2.1

jobs:
  prepare:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Prepare Workspace
          command: echo "Preparing workspace..."

  plan:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Set up HCL Credentials
          command: |
            export HCL_TOKEN=$HCL_TOKEN
            
      - run:
          name: Set up AWS Credentials
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  deploy:
    jobs:
      - prepare
      - plan
      - apply
