version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout

      - run:
          name: Configure AWS Credentials
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

      - run:
          name: Initialize Terraform
          command: terraform init

      - run:
          name: Validate Terraform Files
          command: terraform validate

      - run:
          name: Plan Terraform Changes
          command: terraform plan -out=tfplan

      - run:
          name: Apply Terraform Changes
          command: terraform apply -auto-approve tfplan

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
